# 错误处理

- [错误处理](#错误处理)
  - [一、Panic](#一panic)
  - [二、Result](#二result)
  - [三、Panic or Not to Panic](#三panic-or-not-to-panic)

- Rust中定义 Recoverable 与 Unrecoverable 两种错误，且不提供 exception, 而提供 `Result<T, E>` 与 `panic!` 两种错误处理方式
  - Recoverable Errors: `Result<T, E>`
  - Unrecoverable Errors: `panic!`

## 一、Panic

- `panic`宏执行时，程序会打印一个失败信息，同时 展开(unwind) 并 清空 栈，最后退出
  - unwind
    - rust程序展开展开栈并清理每一个遇到的函数的数据
    - 需要进行大量的工作
  - `aborting`
    - rust允许跳过unwind过程，直接关闭程序而不进行clean up
    - 程序所使用的内存将由操作系统来进行回收
    - `aborting` 舍弃了回收的过程，因此编译得到的代码会变小

```rust
// Cargo.toml
[profile.release]
panic = 'abort'
```

**Panic BackTrace**

> 获取 backtrace 信息必须在程序中留下debug symbols, 使用`--release`则会disable debug symbols

- 运行时使用`RUST_BACKTRACE=1`以进行panic回溯
  - 自顶向下进行阅读，直到找到相应的代码，其上是该段代码所调用的函数信息，其下是该段代码的调用者

## 二、Result

> Result 在 prelude中

- 一些错误的出现易于解释与响应，则没必要使得整个程序退出，对于这种错误的处理，可以使用 Result

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}

let f = File::open("hello.txt");

let f = match f {
    Ok(file) => file,
    Err(error) => panic!("Problem opening the file: {:?}", error),
};
```

**多个不同的错误**

- 嵌套 match

```rust
let f = File::open("hello.txt");

let f = match f {
    Ok(file) => file,
    Err(error) => match error.kind() {
        ErrorKind::NotFound => match File::create("hello.txt") {
            Ok(fc) => fc,
            Err(e) => panic!("Problem creating the file: {:?}", e),
        },
        other_error => {
            panic!("Problem opening the file: {:?}", other_error)
        }
    },
};
```

**便捷处理**

- `unwarp`
  - 如果没有错误，则会返回正常结果
  - 否则则panic

```rust
let f = File::open("hello.txt").unwrap();
```

- `expect`
  - 定义 panic 中的信息

```rust
let f = File::open("hello.txt").expect("Failed to open hello.txt");
```

**错误传播**

- 错误不进行处理，而转交给调用者

```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

- `?` 语法糖，对于返回值为Result的函数，以及调用者返回值为Result的函数
  - 如果函数中，调用的返回值为OK，则OK中的值将作为调用的结果
  - 否则，则对于整个函数而言，会在出错处进行返回
- `?` 会调用实现了`From`特征的from方法
- 在返回值为 Result、Option、FromResidual 的函数中使用

```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}

use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

- 对于main函数
  - `Box<dyn Error>`即任意类型的函数

```rust
fn main() -> Result<(), Box<dyn Error>> {
    let f = File::open("hello.txt")?;

    Ok(())
}
```


## 三、Panic or Not to Panic

- 在Example、Prototye code、与tests中，尽量使用panic
- 使用自定义类型进行验证
  - new、getter方法

- [continue](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html)